# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-01 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('attributename', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('stage', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'stage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpdatedAki',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('procedure_date', models.CharField(blank=True, db_column='Procedure_Date', max_length=45, null=True)),
                ('in_hos_datetime', models.CharField(blank=True, db_column='IN_HOS_DATETIME', max_length=45, null=True)),
                ('out_hos_datetime', models.CharField(blank=True, db_column='OUT_HOS_DATETIME', max_length=45, null=True)),
                ('aki_stage', models.IntegerField(blank=True, null=True)),
                ('field_field', models.FloatField(blank=True, db_column='\u624b\u672f\u5e74\u9f84', null=True)),
                ('field_field_0', models.CharField(blank=True, db_column='\u6027\u522b', max_length=45, null=True)),
                ('anemia', models.IntegerField(blank=True, null=True)),
                ('field_field_1', models.CharField(blank=True, db_column='\u7cd6\u5c3f\u75c5', max_length=45, null=True)),
                ('field_field_2', models.CharField(blank=True, db_column='\u5fc3\u529b\u8870\u7aed', max_length=45, null=True)),
                ('field_iabp_field', models.IntegerField(blank=True, db_column='\u4e3b\u52a8\u8109\u5185\u7403\u56ca\u53cd\u640f(IABP)', null=True)),
                ('hypotension', models.IntegerField(blank=True, null=True)),
                ('field_field_3', models.FloatField(blank=True, db_column='\u5bf9\u6bd4\u5242\u7528\u91cf', null=True)),
                ('gfr', models.FloatField(blank=True, null=True)),
                ('field_field_4', models.IntegerField(blank=True, db_column='\u5fc3\u808c\u6897\u6b7b\u53f2', null=True)),
                ('hypercholesterolemia', models.IntegerField(blank=True, db_column='Hypercholesterolemia', null=True)),
                ('hdl_c', models.FloatField(blank=True, db_column='HDL-C', null=True)),
                ('urgent_pci', models.IntegerField(blank=True, db_column='urgent_PCI', null=True)),
                ('pre_crea', models.FloatField(blank=True, db_column='Pre_Crea', null=True)),
                ('field_field_5', models.CharField(blank=True, db_column='\u9ad8\u8840\u538b', max_length=45, null=True)),
                ('field_field_6', models.CharField(blank=True, db_column='\u4e3b\u52a8\u8109\u7403\u56ca\u53cd\u640f', max_length=45, null=True)),
                ('field_field_7', models.CharField(blank=True, db_column='\u5fc3\u808c\u6897\u6b7b', max_length=45, null=True)),
                ('field_field_8', models.CharField(blank=True, db_column='\u5438\u70df', max_length=45, null=True)),
                ('field_field_9', models.CharField(blank=True, db_column='\u8840\u8102\u5f02\u5e38', max_length=45, null=True)),
                ('field_field_10', models.CharField(blank=True, db_column='\u80be\u529f\u80fd\u5f02\u5e38', max_length=45, null=True)),
                ('field_field_11', models.CharField(blank=True, db_column='\u51a0\u5fc3\u75c5\u5bb6\u65cf\u53f2', max_length=45, null=True)),
                ('field_field_12', models.CharField(blank=True, db_column='\u65e9\u53d1\u51a0\u5fc3\u75c5\u5bb6\u65cf\u53f2', max_length=45, null=True)),
                ('cabg_field', models.CharField(blank=True, db_column='CABG\u624b\u672f\u53f2', max_length=45, null=True)),
                ('field_field_13', models.CharField(blank=True, db_column='\u7cd6\u5c3f\u75c5\u6cbb\u7597\u65b9\u6848', max_length=45, null=True)),
                ('field_field_14', models.CharField(blank=True, db_column='\u51fa\u8840\u6027\u8111\u8840\u7ba1\u75be\u75c5', max_length=45, null=True)),
                ('field_field_15', models.CharField(blank=True, db_column='\u5916\u5468\u52a8\u8109\u75be\u75c5', max_length=45, null=True)),
                ('field_field_16', models.CharField(blank=True, db_column='\u6162\u6027\u80ba\u75c5', max_length=45, null=True)),
                ('field_field_17', models.FloatField(blank=True, db_column='\u5fc3\u7387', null=True)),
                ('field_field_18', models.FloatField(blank=True, db_column='\u6536\u7f29\u538b', null=True)),
                ('field_field_19', models.FloatField(blank=True, db_column='\u8212\u5f20\u538b', null=True)),
                ('field_field_20', models.CharField(blank=True, db_column='\u5bf9\u6bd4\u5242\u7c7b\u578b', max_length=45, null=True)),
                ('field_field_21', models.CharField(blank=True, db_column='\u8bca\u65ad\u6027\u5bfc\u7ba1\u672f', max_length=45, null=True)),
                ('field_field_22', models.CharField(blank=True, db_column='\u9020\u5f71\u7ed3\u8bba', max_length=45, null=True)),
                ('field_field_23', models.FloatField(blank=True, db_column='\u5de6\u4e3b\u5e72\u51a0\u72b6\u52a8\u8109', null=True)),
                ('field_field_24', models.FloatField(blank=True, db_column='\u8fd1\u6bb5\u51a0\u72b6\u52a8\u8109', null=True)),
                ('field_field_25', models.FloatField(blank=True, db_column='\u4e2d\u6bb5/\u8fdc\u6bb5/\u5bf9\u89d2\u652f\u51a0\u72b6\u52a8\u8109', null=True)),
                ('circ_oms_pda_lpl', models.FloatField(blank=True, db_column='Circ.OMs.PDA.LPL', null=True)),
                ('rca_rpda_rpl_am', models.FloatField(blank=True, db_column='RCA.RPDA.RPL.AM', null=True)),
                ('field_field_26', models.CharField(blank=True, db_column='\u6865\u8840\u7ba1', max_length=45, null=True)),
                ('pci_field', models.CharField(blank=True, db_column='PCI\u72b6\u6001', max_length=45, null=True)),
                ('pci_field_0', models.CharField(blank=True, db_column='PCI\u6307\u5f81', max_length=45, null=True)),
                ('d2b_field', models.FloatField(blank=True, db_column='D2B \u65f6\u95f4', null=True)),
                ('field_field_27', models.CharField(blank=True, db_column='\u666e\u901a\u809d\u7d20', max_length=45, null=True)),
                ('field_pci_field', models.CharField(blank=True, db_column='\u963f\u53f8\u5339\u6797(PCI)', max_length=45, null=True)),
                ('field_field_28', models.CharField(blank=True, db_column='\u6bd4\u4f10\u5362\u5b9a', max_length=45, null=True)),
                ('field_field_29', models.CharField(blank=True, db_column='\u76f4\u63a5\u51dd\u8840\u9176\u6291\u5236\u5242', max_length=45, null=True)),
                ('iib_iiia_field', models.CharField(blank=True, db_column='IIb/IIIa\u53d7\u4f53\u62ee\u6297\u5242', max_length=45, null=True)),
                ('field_pci_field_0', models.CharField(blank=True, db_column='\u6c2f\u5421\u683c\u96f7(PCI)', max_length=45, null=True)),
                ('field_pci_field_1', models.CharField(blank=True, db_column='\u666e\u62c9\u683c\u96f7(PCI)', max_length=45, null=True)),
                ('field_field_30', models.CharField(blank=True, db_column='\u66ff\u5361\u683c\u96f7', max_length=45, null=True)),
                ('field_pci_field_2', models.CharField(blank=True, db_column='\u567b\u6c2f\u5421\u5576(PCI)', max_length=45, null=True)),
                ('field_i', models.FloatField(blank=True, db_column='\u672f\u524d\u808c\u9499\u86cb\u767dI', null=True)),
                ('field_field_31', models.FloatField(blank=True, db_column='\u672f\u524d\u8840\u7ea2\u86cb\u767d', null=True)),
                ('field_field_32', models.FloatField(blank=True, db_column='\u672f\u524d\u4f4e\u5bc6\u5ea6\u8102\u86cb\u767d', null=True)),
                ('field_i_0', models.FloatField(blank=True, db_column='\u672f\u540e\u808c\u9499\u86cb\u767dI', null=True)),
                ('field_field_33', models.FloatField(blank=True, db_column='\u672f\u540e\u8840\u7ea2\u86cb\u767d', null=True)),
                ('field_field_34', models.FloatField(blank=True, db_column='\u672f\u540e\u4f4e\u5bc6\u5ea6\u8102\u86cb\u767d', null=True)),
                ('field_field_35', models.CharField(blank=True, db_column='\u5bf9\u6bd4\u5242\u8fc7\u654f', max_length=45, null=True)),
            ],
            options={
                'db_table': 'updated_aki',
                'managed': False,
            },
        ),
    ]
